remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: iTanken's GitHub Home
description: <a href="https://zixizixi.cn" target="_blank">https://zixizixi.cn</a>
show_downloads: true
google_analytics: G-44H17JJEWZ
